[versions]
junit = "6.0.2"


[libraries]
# org.assertj - AssertJ
# https://github.com/assertj/assertj
assertj-core = { module = "org.assertj:assertj-core", version = "3.27.6" }

# org.junit - JUnit
# https://github.com/junit-team/junit5
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
