[versions]
swagger-core = "2.2.41"


[libraries]
# com.osmerion.omittable:omittable-jackson - Omittable - Jackson Integration
# https://github.com/Osmerion/omittable-jackson
omittable-jackson = { module = "com.osmerion.omittable:omittable-jackson", version = "0.5.0" }

# io.swagger.core.v3 - Swagger Core
# https://github.com/swagger-api/swagger-core
swagger-core-jakarta = { module = "io.swagger.core.v3:swagger-core-jakarta", version.ref = "swagger-core" }
